version: "3"
services:
  fluentd:
    build:
      context: ./fluentd/.
      dockerfile: fluentd.dockerfile
    container_name: logmon-fluentd
    hostname: logmon-fluentd
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
    environment:
      - FLUENT_UID=0
    links:
      - elasticsearch
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "5044:5044"
    privileged: true
    depends_on:
      - elasticsearch
    networks:
      - default
    labels:
      org.label-schema.group: "log-monitor"

  elasticsearch:
    image: elasticsearch:7.8.1
    container_name: logmon-elasticsearch
    hostname: logmon-elasticsearch
    volumes:
      - ../data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      # - cluster.initial_master_nodes=logmon-elasticsearch
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - 9200:9200
    networks:
      - default
    labels:
      org.label-schema.group: "log-monitor"

  kibana:
    image: kibana:7.8.1
    container_name: logmon-kibana
    hostname: logmon-kibana
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://logmon-elasticsearch:9200
    restart : always
    ports:
      - 5601:5601
    networks:
      - default
    labels:
      org.label-schema.group: "log-monitor"

  curator:
    build:
      context: ./curator/.
      dockerfile: dockerfile
      args:
        CURATOR_VERSION: 5.7
    container_name: logmon-curator
    hostname: logmon-curator
    links:
      - elasticsearch
    networks:
      - default
    labels:
      org.label-schema.group: "log-monitor"
    depends_on:
      - elasticsearch
    volumes:
      - ./curator:/config

  elastalert:
    build:
      context: ./elastalert/.
      dockerfile: elastalert.dockerfile
    container_name: logmon-elastalert
    hostname: logmon-elastalert
    # environment:
      # - TEAMS_LOG_ALERT_WEBHOOK=${TEAMS_LOG_ALERT_WEBHOOK}
      # - TEAMS_LOG_HEARTBEAT_WEBHOOK=${TEAMS_LOG_HEARTBEAT_WEBHOOK}
    volumes:
      - ./elastalert/config/mailtrap_credentials.yaml:/opt/elastalert/config/mailtrap_credentials.yaml
    networks:
      - default
    labels:
      org.label-schema.group: "log-monitor"

networks:
  default:
    driver: bridge