actions:
  1:
    action: delete_indices
    description: >-
       Delete indices older than ${UNIT_COUNT:1} ${UNIT:months} (based on index name), for logstash-
       prefixed indices. Ignore the error if the filter does not result in an
       actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 1
      exclude:
  2:
    action: delete_indices
    description: >-
      Delete winlogbeat logs
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: True
      disable_action: False
      allow_ilm_indices: True
    filters:
    - filtertype: pattern
      kind: regex
      value: '^winlogbeat[\w\W]*'
      exclude:
    - filtertype: age
      source: field_stats
      direction: older
      unit: days
      unit_count: 1
      field: '@timestamp'
      stats_result: min_value
      exclude: