version: "3"
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.8.1
    container_name: filebeat
    user: root
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ../data/filebeat/:/usr/share/filebeat/data/
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      # - < actual_log_path_in_host >:< log_path_in_container_and_set_in_filebeat_yaml >
    command: 
      - -e=false # set this command to output log to file