version: "3.5"
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.8.1
    container_name: filebeat
    user: root
    environment:
      - TZ=Asia/Taipei
      - FLUENTD_HOST=${FLUENTD_HOST}
      - FLUENTD_PORT=${FLUENTD_PORT}
    volumes:
      - ../data/filebeat/:/usr/share/filebeat/data/
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ${AUTH_LOG_PATH}:/var/log/filebeat/Auth
      - ${BACKEND_LOG_PATH}:/var/log/filebeat/Backend
      # - < actual_log_path_in_host >:< log_path_in_container_and_set_in_filebeat_yaml >
    command: 
      - -strict.perms=false # disable the permission checking
      # - -e=false # set this command to output log to file

networks:
  default:
    name: logmon-filebeat
    driver: bridge